dist: trusty

language: go

go:
  - 1.7.1
  - master

script:
  - go get -d
  - go build

deploy:
  provider: releases
  api_key:
    secure: o0bbfRhleCRGS9fwTE9+eGs1wDnMBGjSnpY04g51QepDKBuTjGhcFIS4zJqbdCowo4QvIEIk6fZZWV0tZBT7bYDBVk9JMumqMx5/CIeP/APHg6RGF1u1nnRTDxNn5qVs3EmRB52uibBa9eRmKKtsBUpRnB02KbHVEGdDyiQlK35dcJIvMlh77AgmMqHVrL0zDDVRe65MG6DOypibvTSKBVUbGy8YxjlFDkvuNy0KeoophD8VGjcdG5UM7iNo4At4JR8HRcW6VIwi3uxQlPz+kUhRAV5cNK4mTHE0jEvWSBh7FnFBMYgliJQ4GiId10HfpGQign686JYa1aTvgKRmQNYE97XJTkcY07hjlg2tc0W+mcJnb7RvKlkHA6FESBLQNqv5Hbp/E0Rr8Lcb+veR/sgzwL/QB6bJ7NWf0X+qzWcMfRqnR5yvVUx696BcRQ24x+P85UYy+C+ZR6xMTFY/aOilc568AKd1TmHLunQxJqVK82qUpS7lq371Uk5WMpnPOSwLqTy/fe65f5ag8vwwpwMhb+/q+ZPrW8o1eUqGhc0uFZabxhCONsORkZXgSHy8fWk6YpOCqRzihNZ4GRr192S0xozjuVD7gimLXuQFvC6Wifo0zebETzv7y1MbPbSZO6vximibDvOqZmWt2RYGfouXzQVfOn6CiDiuljTnadI=
  file: "./trash"
  on:
    repo: karlmutch/trash
    tags: true
